#!/bin/sh
#deploy="false"
deploy="true"

image=mavenproject4
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t abhijari/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push abhijari/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag abhijari/${image}:1.0-SNAPSHOT abhijari/${image}:latest
        docker push abhijari/${image}:latest
    fi
fi