#!/bin/sh
mvn clean package && docker build -t abhijari/mavenproject4 .
docker rm -f mavenproject4 2>/dev/null || true && docker run -it --name mavenproject4 -p 8080:8080 -p 4848:4848 -p 8181:8181 --name mavenproject4 abhijari/mavenproject4
